# Generated by Django 3.1 on 2020-12-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identification',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
