# Generated by Django 3.1 on 2020-12-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_review_module_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='images/network/default_image.png', upload_to='images/network'),
        ),
    ]
