# Generated by Django 3.1 on 2020-12-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='network/images/network/default_image.png', upload_to='images/'),
        ),
    ]
