# Generated by Django 3.1 on 2020-12-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20201217_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='network/images/network/default_image.png', upload_to='network/images/network/'),
        ),
    ]
