# Generated by Django 3.1 on 2020-12-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20201217_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='images/default_image.png', upload_to='images/'),
        ),
    ]
